---

- hosts: all
  become: true 
  tasks:

    - name: update php support for apache
      package:  
        name:
          - "{{ apache_package }}" 
          - "{{ php_package }}"
        state: latest
        update_cache: yes
               
